name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: render-examples/deploy-to-render@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: "your-render-service-id"
